server:
  port: 9080
  servlet:
    context-path: '/study-demo'

spring:
  application:
    name: Java Project Study Demo

  datasource:
    url: jdbc:mysql://localhost:3306/study_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hanxw.project.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
