server:
  port: 8080

spring:
  application:
    name: project-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# MyBatis Plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Dubbo 配置
dubbo:
  application:
    name: project-web
    qos-enable: false
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
    timeout: 3000
    retries: 2
  scan:
    base-packages: com.hanxw.project.web

logging:
  level:
    com.hanxw.project: DEBUG
